version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jean
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
